input_shape: 
  200
  320
  3

num_poolings: 6

convert_bboxes_to_relative_bboxes: True

num_anchors: 10
num_classes: 10

batch_size: 128
lr: 1e-3
reg_coef: 4e-4
dropout_rate: 0.15

validation_split: 0.15

use_data_aug: True

train_with_masks: True
training_phase_2: True

training_phase_2_lr_divisor: 1e1

threshold_conf: 0.5
threshold_nms: 0.5

num_generating: 200_000
generating_index: 0
do_generate: True
do_generate_en_cards: True
do_generate_per_cards: True
do_generate_national_ID_cards: True

monitor_metric: "val_bboxes_loss"

model_name: "sliding_window_ocr_model"

random_seed: 42

gpu_memory_limit: 6144

